// flow-typed signature: 5c81b4da2049801d834416c30bf0bec0
// flow-typed version: <<STUB>>/babel-minify_v^0.1.12/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-minify/lib/cli' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/index' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/parse-argv' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/tasks' {
  declare module.exports: any;
}

declare module 'babel-minify/lib/yargs' {
  declare module.exports: any;
}

declare module 'babel-minify/src/cli' {
  declare module.exports: any;
}

declare module 'babel-minify/src/index' {
  declare module.exports: any;
}

declare module 'babel-minify/src/parse-argv' {
  declare module.exports: any;
}

declare module 'babel-minify/src/tasks' {
  declare module.exports: any;
}

declare module 'babel-minify/src/yargs' {
  declare module.exports: any;
}

declare module 'babel-minify/test/cli' {
  declare module.exports: any;
}

declare module 'babel-minify/test/jsapi' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-minify/lib/cli.js' {
  declare module.exports: $Exports<'babel-minify/lib/cli'>;
}
declare module 'babel-minify/lib/index.js' {
  declare module.exports: $Exports<'babel-minify/lib/index'>;
}
declare module 'babel-minify/lib/parse-argv.js' {
  declare module.exports: $Exports<'babel-minify/lib/parse-argv'>;
}
declare module 'babel-minify/lib/tasks.js' {
  declare module.exports: $Exports<'babel-minify/lib/tasks'>;
}
declare module 'babel-minify/lib/yargs.js' {
  declare module.exports: $Exports<'babel-minify/lib/yargs'>;
}
declare module 'babel-minify/src/cli.js' {
  declare module.exports: $Exports<'babel-minify/src/cli'>;
}
declare module 'babel-minify/src/index.js' {
  declare module.exports: $Exports<'babel-minify/src/index'>;
}
declare module 'babel-minify/src/parse-argv.js' {
  declare module.exports: $Exports<'babel-minify/src/parse-argv'>;
}
declare module 'babel-minify/src/tasks.js' {
  declare module.exports: $Exports<'babel-minify/src/tasks'>;
}
declare module 'babel-minify/src/yargs.js' {
  declare module.exports: $Exports<'babel-minify/src/yargs'>;
}
declare module 'babel-minify/test/cli.js' {
  declare module.exports: $Exports<'babel-minify/test/cli'>;
}
declare module 'babel-minify/test/jsapi.js' {
  declare module.exports: $Exports<'babel-minify/test/jsapi'>;
}
